### PR TITLE
Only deploy from master

### PR DESCRIPTION
**Pull request by noamross**
The book should only deploy from changes to the master branch.  Ironically, this change can not be tested.

### CODE REVIEW

**Comment by noamross** [comment]
There doesn't seem to be any **tic** setting for this.

**Comment by maelle** [comment]
Thanks! cc @krlmlr 

Btw Noam I think the .gitignore can/should still contain "_book" which is the case in the example repo 🤔

**Comment by krlmlr** [comment]
You can use `if()` in `tic.R`, the condition would be `if (ci()$get_branch() == "master") ...` .

**Comment by maelle** [comment]
I added that condition around everything that was in tic.R

**Pull request merged**
